Repository googleapis/nodejs-scheduler, pull requests merged in 2019-03, with the labels that each got.

#53 docs: update comments on protos
  protos/google/cloud/scheduler/v1beta1/cloudscheduler.proto
  protos/google/cloud/scheduler/v1beta1/job.proto
  protos/google/cloud/scheduler/v1beta1/target.proto
  src/v1beta1/cloud_scheduler_client.js
  src/v1beta1/doc/google/cloud/scheduler/v1beta1/doc_cloudscheduler.js
  src/v1beta1/doc/google/cloud/scheduler/v1beta1/doc_job.js
  src/v1beta1/doc/google/cloud/scheduler/v1beta1/doc_target.js
  synth.metadata
Labels: cla: yes

#55 build(ci): use node10 for system-test and samples-test
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/lint.cfg
  .kokoro/continuous/node10/samples-test.cfg
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/samples-test.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test.cfg
Labels: cla: yes

#54 build: update release config
  .kokoro/release/publish.cfg
  synth.metadata
Labels: automerge, cla: yes

#56 build: Add docuploader credentials to node publish jobs
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#59 feat: add v1 version of API
  protos/google/cloud/scheduler/v1/cloudscheduler.proto
  protos/google/cloud/scheduler/v1/job.proto
  protos/google/cloud/scheduler/v1/target.proto
  src/index.js
  src/v1/cloud_scheduler_client.js
  src/v1/cloud_scheduler_client_config.json
  src/v1/doc/google/cloud/scheduler/v1/doc_cloudscheduler.js
  src/v1/doc/google/cloud/scheduler/v1/doc_job.js
  src/v1/doc/google/cloud/scheduler/v1/doc_target.js
  src/v1/doc/google/protobuf/doc_any.js
  src/v1/doc/google/protobuf/doc_duration.js
  src/v1/doc/google/protobuf/doc_empty.js
  src/v1/doc/google/protobuf/doc_field_mask.js
  src/v1/doc/google/protobuf/doc_timestamp.js
  src/v1/doc/google/rpc/doc_status.js
  src/v1/index.js
  synth.metadata
  synth.py
  test/gapic-v1.js
Labels: cla: yes

#61 Release @google-cloud/scheduler v0.2.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#62 refactor: update json import paths
  src/v1/cloud_scheduler_client.js
  src/v1beta1/cloud_scheduler_client.js
  synth.metadata
Labels: cla: yes

#63 build: use per-repo npm publish token
  .kokoro/release/publish.cfg
Labels: cla: yes

#66 chore: use wombat to publish to npm
  .kokoro/publish.sh
Labels: cla: yes

#68 fix: include 'x-goog-request-params' header in requests
  src/v1/cloud_scheduler_client.js
  src/v1beta1/cloud_scheduler_client.js
  synth.metadata
Labels: cla: yes
