Repository googleapis/nodejs-scheduler, pull requests merged in 2019-05, with the labels that each got.

#83 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#82 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#86 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#89 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: automerge, cla: yes

#91 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#90 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#88 build: only pipe to codecov if tests run on Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#92 feat: DEADLINE_EXCEEDED is no longer retried; attemptDeadline option has been introduced
  protos/google/cloud/scheduler/v1/cloudscheduler.proto
  protos/google/cloud/scheduler/v1/job.proto
  protos/google/cloud/scheduler/v1/target.proto
  src/v1/cloud_scheduler_client_config.json
  src/v1/doc/google/cloud/scheduler/v1/doc_job.js
  src/v1/doc/google/cloud/scheduler/v1/doc_target.js
  src/v1beta1/cloud_scheduler_client_config.json
  synth.metadata
Labels: cla: yes

#94 fix: DEADLINE_EXCEEDED retry code is idempotent
  src/v1/cloud_scheduler_client_config.json
  src/v1beta1/cloud_scheduler_client_config.json
  synth.metadata
Labels: cla: yes

#95 chore: release 1.0.0
  .repo-metadata.json
  CHANGELOG.md
  README.md
  package.json
  samples/package.json
  synth.metadata
Labels: autorelease: pending, cla: yes

#97 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#98 refactor: drop dependency on lodash.merge and update links
  package.json
  src/v1/cloud_scheduler_client.js
  src/v1beta1/cloud_scheduler_client.js
  synth.metadata
Labels: cla: yes

#99 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#100 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#101 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#102 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
