Repository googleapis/nodejs-scheduler, pull requests merged in 2019-04, with the labels that each got.

#70 feat(v1beta1): added oauthToken, oidcToken and attemptDeadline
  .gitignore
  protos/google/cloud/scheduler/v1beta1/cloudscheduler.proto
  protos/google/cloud/scheduler/v1beta1/job.proto
  protos/google/cloud/scheduler/v1beta1/target.proto
  src/v1beta1/cloud_scheduler_client.js
  src/v1beta1/doc/google/cloud/scheduler/v1beta1/doc_cloudscheduler.js
  src/v1beta1/doc/google/cloud/scheduler/v1beta1/doc_job.js
  src/v1beta1/doc/google/cloud/scheduler/v1beta1/doc_target.js
  synth.metadata
Labels: automerge, cla: yes

#71 Release @google-cloud/scheduler v0.3.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#72 chore(vuln): upgrade some dependencies with vulnerabilities
  package.json
Labels: automerge, cla: yes

#69 refactor: use execSync for tests
  samples/package.json
  samples/system-test/test.samples.js
Labels: cla: yes

#73 refactor: wrap execSync with encoding: utf-8
  samples/system-test/test.samples.js
Labels: automerge, cla: yes

#75 chore(docs): formatting updates
  src/v1/doc/google/protobuf/doc_any.js
  src/v1/doc/google/protobuf/doc_field_mask.js
  src/v1/doc/google/protobuf/doc_timestamp.js
  src/v1beta1/doc/google/protobuf/doc_any.js
  src/v1beta1/doc/google/protobuf/doc_field_mask.js
  src/v1beta1/doc/google/protobuf/doc_timestamp.js
  synth.metadata
Labels: cla: yes

#76 build: remove circleCI config
  .circleci/npm-install-retry.js
Labels: cla: yes

#77 build: use repo-metadata to generate README
  .cloud-repo-tools.json
  .repo-metadata.json
  README.md
  package.json
  samples/README.md
  src/v1/cloud_scheduler_client.js
  src/v1beta1/cloud_scheduler_client.js
  synth.metadata
Labels: cla: yes

#78 docs: update to useful quickstart
  README.md
  samples/README.md
  samples/createJob.js
  samples/deleteJob.js
  samples/quickstart.js
Labels: automerge, cla: yes

#79 update to .nycrc with --all enabled
  .nycrc
Labels: cla: yes
