Repository googleapis/nodejs-scheduler, pull requests merged in 2020-11, with the labels that each got.

#303 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: cloudscheduler, automerge, cla: yes, context: full

#305 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v1/cloud_scheduler_client.ts
  src/v1beta1/cloud_scheduler_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: cloudscheduler, automerge, cla: yes

#313 fix(browser): check for fetch on window
  README.md
  protos/protos.json
  src/v1/cloud_scheduler_client.ts
  src/v1beta1/cloud_scheduler_client.ts
  synth.metadata
Labels: api: cloudscheduler, cla: yes, context: partial
