Repository googleapis/nodejs-scheduler, pull requests merged in 2020-05, with the labels that each got.

#248 fix: regen protos and tests, formatting
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
  test/gapic_cloud_scheduler_v1.ts
  test/gapic_cloud_scheduler_v1beta1.ts
Labels: automerge, cla: yes

#249 chore: code formatting
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: cla: yes, context: none

#250 fix: synth.py clean up for multiple version
  src/index.ts
  synth.metadata
  synth.py
Labels: cla: yes

#251 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
