Repository googleapis/nodejs-scheduler, pull requests merged in 2020-09, with the labels that each got.

#292 build(test): recursively find test files; fail on unsupported dependency versions
  .github/workflows/ci.yaml
  .mocharc.js
  synth.metadata
Labels: automerge, cla: yes, context: full

#265 feat: add sample for updateJob
  samples/test/test.samples.js
  samples/updateJob.js
Labels: api: cloudscheduler, cla: yes, samples

#293 docs: update list of available samples
  README.md
  samples/README.md
  synth.metadata
Labels: cla: yes, context: none
