Repository googleapis/nodejs-scheduler, pull requests merged in 2020-07, with the labels that each got.

#267 build: use bazel build
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#268 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#271 build: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#274 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#276 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#277 build: missing parenthesis in publish script, delete Node 8 tests, add config for cloud-rad for nodejs
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#278 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#279 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#280 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#281 build: update protos
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: none
